name: steps_count
description: "A Flutter plugin for counting steps and managing background step tracking services on Android devices."
version: 0.0.2
homepage: https://www.dajiraj.com
repository: https://github.com/Dajiraj-Infotech/steps_count
issue_tracker: https://github.com/Dajiraj-Infotech/steps_count/issues

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dajiraj.steps_count
        pluginClass: StepsCountPlugin
      ios:
        pluginClass: StepsCountPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
